import{a as g,S as h,i}from"./assets/vendor-DvfmeZXB.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function m(e,n){const o="https://pixabay.com",r="/api/",t=new URLSearchParams({key:"53366828-bd78e2a0684a00ed0fbe9f50e",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:n}),s=`${o}${r}?${t}`;return(await g.get(s)).data}const L=new h(".gallery a",{captionsData:"alt",captionPosition:"bottom"});function p(e){const n=document.querySelector(".gallery"),o=e.map(r=>`
      <li>
        <a href="${r.largeImageURL}" title="${r.tags}">
          <img src="${r.webformatURL}" alt="${r.tags}">
        </a>
        <div class="info">
          <p>Likes: <span class="value">${r.likes}</span></p>
          <p>Views: <span class="value">${r.views}</span></p>
          <p>Comments: <span class="value">${r.comments}</span></p>
          <p>Downloads: <span class="value">${r.downloads}</span></p>
        </div>
      </li>
    `).join("");n.insertAdjacentHTML("beforeend",o),L.refresh()}function b(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){document.querySelector(".loader").classList.remove("is-hidden"),u()}function y(){document.querySelector(".loader").classList.add("is-hidden")}function v(){document.querySelector(".js-btn-load").classList.remove("is-hidden")}function u(){document.querySelector(".js-btn-load").classList.add("is-hidden")}const w=document.querySelector(".form"),S=document.querySelector('input[name="search-text"]');document.querySelector("[data-js-gallery]");const q=document.querySelector(".js-btn-load");let l,a=1,d=0;w.addEventListener("submit",async e=>{if(e.preventDefault(),l=new FormData(e.target).get("search-text").trim(),a=1,!l){i.error({message:"Please enter text!",position:"topCenter"});return}b(),u(),f(),S.value="";try{const o=await m(l,a);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",backgroundColor:"red",timeout:3e3,pauseOnHover:!0,messageColor:"white"});return}p(o.hits),d=Math.ceil(o.totalHits/15),a<d&&v()}catch(o){console.error(o),i.error({message:"Not connecting, Please try again!",position:"center",backgroundColor:"yellow"})}finally{y()}});q.addEventListener("click",async()=>{a++,f();try{const e=await m(l,a);p(e.hits);const n=document.querySelector(".gallery li");if(n){const o=n.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}a>=d&&(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}catch(e){console.error(e),i.error({message:"Error loading more images.",position:"center"})}finally{y()}});
//# sourceMappingURL=index.js.map
